import { useCallback,useEffect,useMemo,useState } from "react";
import { Link } from "react-router-dom";
import { AppShell } from "@/components/AppShell";
import { PostAdsDialog } from "@/components/trade/PostAdsDialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { ArrowRight,ChevronDown,ClipboardList,Clock,Filter,Lock,MoreHorizontal,Search,Shield,TrendingUp,Users } from "lucide-react";
import { shortAddress,wallet,useWallet } from "@/lib/useWallet";
import { buyP2PListing,formatINR,formatUSDC,getP2PListings,getP2PPrice,parseUSDC,P2P_PAYMENT_METHODS,type P2PListing,type P2POrder } from "@/lib/p2pApi";

function errorMessage(error:unknown){return error instanceof Error?error.message:"Something went wrong"}
export default function P2P(){
	const account=useWallet();const [mode,setMode]=useState<"buy"|"sell">("buy");const [price,setPrice]=useState("");const [priceDate,setPriceDate]=useState("");const [listings,setListings]=useState<P2PListing[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [payment,setPayment]=useState("All");const [amount,setAmount]=useState("");const [bankOption,setBankOption]=useState("UPI");const [postOpen,setPostOpen]=useState(false);const [selected,setSelected]=useState<P2PListing|null>(null);const [quantity,setQuantity]=useState("");const [buying,setBuying]=useState(false);const [order,setOrder]=useState<P2POrder|null>(null);
	const usdcBalance=account.balances.find(b=>b.asset==="USDC");const totalUSDC=usdcBalance?.amount??0;const availableUSDC=usdcBalance?.available??0;
	const load=useCallback(async()=>{try{setLoading(true);setError("");const [{price:today},{listings:ads}]=await Promise.all([getP2PPrice(),getP2PListings()]);setPrice(today.price);setPriceDate(today.priceDate);setListings(ads)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[]);
	useEffect(()=>{void load()},[load]);
	const filtered=useMemo(()=>listings.filter(l=>(payment==="All"||l.paymentMethod===payment)&&(!amount||Number(formatUSDC(l.remainingRaw))>=Number(amount))),[listings,payment,amount]);
	const totalAvailable=useMemo(()=>listings.reduce((sum,item)=>sum+Number(formatUSDC(item.remainingRaw)),0),[listings]);
	const gross=Number(quantity||0)*Number(selected?.price||0);const max=selected?Number(formatUSDC(selected.remainingRaw)):0;const canBuy=!!selected&&!!account.userId&&account.userId!==selected.sellerId&&Number(quantity)>0&&Number(quantity)<=max;
	function openBuy(listing:P2PListing){setSelected(listing);setQuantity(formatUSDC(listing.remainingRaw));setOrder(null);setError("")}
	async function openPost(){
		if(!account.userId){setError("Connect and authenticate a wallet before posting an ad");return}
		try{await wallet.refreshBalances()}catch{/* The dialog can still show the last successfully loaded balance. */}
		setPostOpen(true)
	}
	async function buy(){if(!selected)return;try{setBuying(true);setError("");const response=await buyP2PListing(selected.id,parseUSDC(quantity));setOrder(response.order);await Promise.all([load(),wallet.refreshBalances()])}catch(e){setError(errorMessage(e))}finally{setBuying(false)}}
	return <AppShell><Marketplace mode={mode} setMode={setMode} price={price} priceDate={priceDate} listings={filtered} loading={loading} error={error} userId={account.userId} payment={payment} setPayment={setPayment} amount={amount} setAmount={setAmount} bankOption={bankOption} setBankOption={setBankOption} totalAvailable={totalAvailable} onBuy={openBuy} onPost={openPost}/><PostAdsDialog open={postOpen} onOpenChange={setPostOpen} price={price} totalUSDC={totalUSDC} availableUSDC={availableUSDC} initialAmount={amount} initialPayment={bankOption as (typeof P2P_PAYMENT_METHODS)[number]} onCreated={()=>{void load();void wallet.refreshBalances()}}/><BuyDialog listing={selected} quantity={quantity} setQuantity={setQuantity} gross={gross} canBuy={canBuy} buying={buying} order={order} userId={account.userId} error={error} onBuy={buy} onClose={()=>{setSelected(null);setOrder(null);setError("")}}/></AppShell>;
}

type MarketplaceProps={mode:"buy"|"sell";setMode:(v:"buy"|"sell")=>void;price:string;priceDate:string;listings:P2PListing[];loading:boolean;error:string;userId?:string;payment:string;setPayment:(v:string)=>void;amount:string;setAmount:(v:string)=>void;bankOption:string;setBankOption:(v:string)=>void;totalAvailable:number;onBuy:(v:P2PListing)=>void;onPost:()=>void};

function Marketplace({mode,setMode,price,priceDate,listings,loading,error,userId,payment,setPayment,amount,setAmount,bankOption,setBankOption,totalAvailable,onBuy,onPost}:MarketplaceProps){
	return <div className="min-h-screen bg-gradient-to-b from-background via-background/95 to-background p-6"><div className="mx-auto max-w-7xl">
	<div className="mb-8 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><h1 className="mb-2 text-4xl font-bold tracking-tight">{mode==="buy"?"Buy":"Sell"} Crypto</h1><p className="text-muted-foreground">{mode==="buy"?"Buy crypto securely from P2P sellers in your local currency.":"Sell your crypto and receive payment in your local currency."}</p></div><div className="flex items-center gap-2"><Button asChild variant="ghost" className="h-10 gap-2 text-primary hover:bg-primary/10 hover:text-primary"><Link to="/p2p/orders"><ClipboardList className="h-4 w-4"/>Orders</Link></Button><Button asChild variant="ghost" className="h-10 gap-2 text-muted-foreground hover:bg-primary/10 hover:text-primary"><Link to="/p2p/advertiser"><MoreHorizontal className="h-4 w-4"/>My Ads<ChevronDown className="h-3.5 w-3.5"/></Link></Button><Button variant="ghost" onClick={onPost} className="h-10 text-primary hover:bg-primary/10">Post Ads</Button></div></div>
	<div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2">
	<div className="flex gap-3"><Button onClick={()=>setMode("buy")} className={`h-11 min-w-36 px-10 font-semibold ${mode==="buy"?"bg-buy text-buy-foreground hover:bg-buy/90":"bg-muted text-muted-foreground hover:bg-muted/80"}`}>Buy</Button><Button onClick={()=>setMode("sell")} className={`h-11 min-w-36 px-10 font-semibold ${mode==="sell"?"bg-red-500 text-white hover:bg-red-600":"border border-border"}`} variant={mode==="sell"?"default":"outline"}>Sell</Button></div>
	<Card className="border-border/50 bg-card/30 p-6 backdrop-blur-sm"><div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-2"><div className="space-y-2"><label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Fiat</label><Select value="inr"><SelectTrigger className="bg-background/50"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="inr">INR (₹)</SelectItem></SelectContent></Select></div><div className="space-y-2"><label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{mode==="buy"?"Minimum available":"Crypto amount"}</label><Input placeholder={mode==="buy"?"Enter USDC amount":"Enter USDC amount to sell"} type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="bg-background/50"/></div></div><Button onClick={mode==="sell"?onPost:undefined} className="w-full bg-primary text-primary-foreground hover:bg-primary/90"><Search className="mr-2 h-4 w-4"/>{mode==="sell"?"Post Sell Ad":"Search"}</Button></Card>
	<div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary"><Users className="mr-1 h-3 w-3"/>P2P sellers</Badge><Button variant="ghost" size="sm" className="h-8"><Filter className="mr-1 h-4 w-4"/>Filter</Button></div><Button variant="ghost" size="sm" className="h-8">Sort: Best price<ChevronDown className="ml-1 h-4 w-4"/></Button></div><div className="flex flex-wrap gap-2">{["All",...P2P_PAYMENT_METHODS].map(method=><button key={method} onClick={()=>setPayment(method)} className={`rounded-lg px-4 py-2 text-sm font-medium transition-all ${payment===method?"bg-primary text-primary-foreground":"bg-muted/30 text-muted-foreground hover:bg-muted/50"}`}>{method}</button>)}</div></div>
	<ListingsTable listings={listings} userId={userId} loading={loading} mode={mode} onBuy={onBuy} onPost={onPost}/>{error&&<div className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
	</div><MarketplaceSidebar mode={mode} price={price} priceDate={priceDate} amount={amount} setAmount={setAmount} bankOption={bankOption} setBankOption={setBankOption} listings={listings} totalAvailable={totalAvailable} onBuy={onBuy} onPost={onPost}/></div>
	<HowItWorks/></div></div>;
}

function ListingsTable({listings,userId,loading,mode,onBuy,onPost}:{listings:P2PListing[];userId?:string;loading:boolean;mode:"buy"|"sell";onBuy:(v:P2PListing)=>void;onPost:()=>void}){
	return <Card className="overflow-hidden border-border/50 bg-card/20 backdrop-blur-sm"><div className="overflow-x-auto scrollbar-none"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b border-border/30 bg-muted/20"><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">Advertiser</th><th className="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-muted-foreground">Price / Available</th><th className="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-muted-foreground">Payment</th><th className="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-muted-foreground">Trade</th></tr></thead><tbody>
	{loading?<tr><td colSpan={4} className="p-8 text-center text-muted-foreground">Loading database listings…</td></tr>:listings.length===0?<tr><td colSpan={4} className="p-8 text-center text-muted-foreground">No active sell ads found.</td></tr>:listings.map(listing=>{const own=userId===listing.sellerId;const initials=listing.sellerAddress.slice(2,4).toUpperCase();return <tr key={listing.id} className="border-b border-border/20 transition-colors hover:bg-muted/10"><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-primary text-xs font-bold text-primary-foreground">{initials}</div><div><div className="flex items-center gap-2 font-semibold">{shortAddress(listing.sellerAddress)}<Shield className="h-3 w-3 text-primary"/></div><div className="text-xs text-muted-foreground">Listed {new Date(listing.createdAt).toLocaleString()}</div></div></div></td><td className="px-4 py-4 text-center"><div className="font-semibold">{formatINR(listing.price)}</div><div className="text-xs text-muted-foreground">{formatUSDC(listing.remainingRaw)} {listing.asset}</div></td><td className="px-4 py-4 text-center"><Badge variant="secondary" className="text-xs">{listing.paymentMethod}</Badge></td><td className="px-4 py-4 text-center"><Button size="sm" disabled={mode==="buy"&&own} onClick={()=>mode==="buy"?onBuy(listing):onPost()} className={`text-xs ${mode==="buy"?"bg-buy text-buy-foreground hover:bg-buy/90":"bg-red-500 text-white hover:bg-red-600"}`}>{mode==="buy"?(own?"YOUR AD":"BUY USDC"):"SELL USDC"}</Button></td></tr>})}
	</tbody></table></div></Card>;
}

type SidebarProps={mode:"buy"|"sell";price:string;priceDate:string;amount:string;setAmount:(v:string)=>void;bankOption:string;setBankOption:(v:string)=>void;listings:P2PListing[];totalAvailable:number;onBuy:(v:P2PListing)=>void;onPost:()=>void};
function MarketplaceSidebar({mode,price,priceDate,amount,setAmount,bankOption,setBankOption,listings,totalAvailable,onBuy,onPost}:SidebarProps){const gross=Number(amount||0)*Number(price||0);const match=listings.find(item=>item.paymentMethod===bankOption&&Number(formatUSDC(item.remainingRaw))>=Number(amount||0));return <div className="space-y-6">
	<Card className="border-border/50 bg-card/30 p-6 backdrop-blur-sm"><span className="text-sm font-medium text-muted-foreground">Today’s Price</span><div className="mt-4 flex items-baseline gap-2"><span className="text-3xl font-bold">{price?formatINR(price):"Unavailable"}</span><span className="text-sm text-muted-foreground">/USDC</span></div><p className="pt-2 text-xs text-muted-foreground">Database price for {priceDate||"today"}</p></Card>
	<Card className="border-border/50 bg-card/30 p-6 backdrop-blur-sm"><h3 className="mb-4 flex items-center gap-2 font-semibold"><TrendingUp className="h-4 w-4 text-primary"/>{mode==="buy"?"Quick Trade":"Quick Sell"}</h3><div className="space-y-4"><div><label className="mb-2 block text-xs font-medium text-muted-foreground">Bank / Payment Option</label><Select value={bankOption} onValueChange={setBankOption}><SelectTrigger className="bg-background/50"><SelectValue/></SelectTrigger><SelectContent>{P2P_PAYMENT_METHODS.map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-2 block text-xs font-medium text-muted-foreground">{mode==="buy"?"I want to buy":"I want to sell"}</label><div className="flex gap-2"><Input value={amount} onChange={e=>setAmount(e.target.value)} type="number" placeholder="0.00" className="bg-background/50"/><span className="flex items-center rounded-md bg-muted/30 px-3">USDC</span></div></div><div><label className="mb-2 block text-xs font-medium text-muted-foreground">{mode==="buy"?"I will pay":"Gross value"}</label><div className="flex gap-2"><Input readOnly value={gross?gross.toFixed(2):""} placeholder="0.00" className="bg-background/50"/><span className="flex items-center rounded-md bg-muted/30 px-3">INR</span></div></div></div><div className="my-4 rounded-lg bg-muted/20 p-3"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Reference Price</span><span className="font-semibold">{price?formatINR(price):"—"}</span></div><div className="flex justify-between text-xs"><span className="text-muted-foreground">Fee</span><span className="font-semibold">1%</span></div></div><Button disabled={mode==="buy"&&!match} onClick={()=>mode==="buy"&&match?onBuy(match):onPost()} className={`w-full ${mode==="buy"?"bg-buy text-buy-foreground hover:bg-buy/90":"bg-red-500 text-white hover:bg-red-600"}`}>{mode==="buy"?"Proceed to Buy":"Proceed to Sell"}<ArrowRight className="ml-2 h-4 w-4"/></Button></Card>
	<TrustAndSnapshot activeAds={listings.length} totalAvailable={totalAvailable}/></div>}

function TrustAndSnapshot({activeAds,totalAvailable}:{activeAds:number;totalAvailable:number}){return <><Card className="border-border/50 bg-card/30 p-6 backdrop-blur-sm"><h3 className="mb-4 font-semibold">Trust & Safety</h3><div className="space-y-3"><Safety icon={Lock} title="Reserved Balance" text="Listed USDC is reserved securely"/><Safety icon={Shield} title="Authenticated Sellers" text="Every ad belongs to a DEX wallet user"/><Safety icon={Clock} title="Instant Token Transfer" text="USDC moves when a buy is confirmed"/></div></Card><Card className="border-border/50 bg-card/30 p-6 backdrop-blur-sm"><h3 className="mb-4 font-semibold">Market Snapshot</h3><div className="grid grid-cols-2 gap-4"><div><p className="text-xs text-muted-foreground">Available USDC</p><p className="text-lg font-semibold">{totalAvailable.toLocaleString()}</p></div><div><p className="text-xs text-muted-foreground">Active Ads</p><p className="text-lg font-semibold">{activeAds}</p></div><div><p className="text-xs text-muted-foreground">Buyer Fee</p><p className="text-lg font-semibold text-green-500">1%</p></div><div><p className="text-xs text-muted-foreground">Seller Fee</p><p className="text-lg font-semibold">1%</p></div></div></Card></>}
function Safety({icon:Icon,title,text}:{icon:typeof Lock;title:string;text:string}){return <div className="flex items-start gap-3"><Icon className="mt-0.5 h-5 w-5 flex-shrink-0 text-primary"/><div><p className="text-sm font-semibold">{title}</p><p className="text-xs text-muted-foreground">{text}</p></div></div>}

function HowItWorks(){const steps=[{icon:Search,title:"Choose Offer",text:"Choose a live sell ad and enter the USDC quantity."},{icon:Clock,title:"Pay Seller",text:"Pay using the seller’s selected payment method."},{icon:Lock,title:"Receive Crypto",text:"The purchased USDC is credited to your DEX wallet."}];return <div className="mb-12 mt-24 grid grid-cols-1 gap-6 md:grid-cols-3">{steps.map(({icon:Icon,title,text},index)=><div key={title} className="relative"><Card className="flex h-full flex-col items-center border-border/50 bg-card/30 p-8 text-center backdrop-blur-sm"><div className="mb-4 rounded-full bg-primary/10 p-3"><Icon className="h-6 w-6 text-primary"/></div><h3 className="mb-2 text-lg font-semibold">{title}</h3><p className="text-sm leading-relaxed text-muted-foreground">{text}</p></Card>{index<2&&<div className="absolute right-0 top-1/2 hidden h-0.5 w-8 translate-x-1/2 bg-border/30 md:block"/>}</div>)}</div>}

type BuyDialogProps={listing:P2PListing|null;quantity:string;setQuantity:(v:string)=>void;gross:number;canBuy:boolean;buying:boolean;order:P2POrder|null;userId?:string;error:string;onBuy:()=>void;onClose:()=>void};
function BuyDialog({listing,quantity,setQuantity,gross,canBuy,buying,order,userId,error,onBuy,onClose}:BuyDialogProps){return <Dialog open={!!listing} onOpenChange={open=>!open&&onClose()}><DialogContent className="max-w-lg overflow-hidden border-border/50 bg-card/95 shadow-2xl backdrop-blur-xl"><DialogHeader><DialogTitle>{order?"Purchase Completed":"Buy USDC"}</DialogTitle></DialogHeader>{listing&&(order?<div className="space-y-4"><div className="rounded-xl border border-buy/30 bg-buy/10 p-5 text-center"><p className="text-lg font-bold text-buy">{formatUSDC(order.amountRaw)} USDC credited</p><p className="mt-1 text-xs text-muted-foreground">Order {order.id}</p></div><SummaryRow label="Pay using" value={order.paymentMethod}/><SummaryRow label="Gross amount" value={formatINR(order.grossAmount)}/><SummaryRow label="Buyer fee (1%)" value={formatINR(order.buyerFee)}/><SummaryRow label="You pay" value={formatINR(order.buyerPayable)} strong/><p className="text-xs text-muted-foreground">Fiat payment is completed outside the app using the seller’s selected method.</p><Button className="w-full bg-buy text-buy-foreground hover:bg-buy/90" onClick={onClose}>Done</Button></div>:<div className="space-y-5"><div className="rounded-xl border border-border bg-muted/30 p-4 text-sm"><SummaryRow label="Advertiser" value={shortAddress(listing.sellerAddress)}/><SummaryRow label="Price" value={`${formatINR(listing.price)} / USDC`}/><SummaryRow label="Payment" value={listing.paymentMethod}/></div><div><label className="mb-2 block text-xs font-semibold uppercase tracking-wide text-muted-foreground">USDC quantity</label><Input type="number" min="0" step="0.000001" max={formatUSDC(listing.remainingRaw)} value={quantity} onChange={e=>setQuantity(e.target.value)} className="bg-background/50"/><p className="mt-1 text-xs text-muted-foreground">Available {formatUSDC(listing.remainingRaw)} USDC</p></div><div className="rounded-xl border border-border p-4 text-sm"><SummaryRow label="Gross" value={formatINR(gross)}/><SummaryRow label="Buyer fee (1%)" value={formatINR(gross*.01)}/><SummaryRow label="You pay" value={formatINR(gross*1.01)} strong/></div>{userId===listing.sellerId&&<p className="text-sm text-destructive">You cannot buy your own ad.</p>}{!userId&&<p className="text-sm text-destructive">Connect and authenticate a wallet to buy.</p>}{error&&<p className="text-sm text-destructive">{error}</p>}<Button className="w-full bg-buy text-buy-foreground hover:bg-buy/90" disabled={!canBuy||buying} onClick={onBuy}>{buying?"Processing…":`Buy USDC • ${formatINR(gross*1.01)}`}</Button></div>)}</DialogContent></Dialog>}
function SummaryRow({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`flex justify-between gap-4 py-1.5 ${strong?"font-semibold":""}`}><span className="text-muted-foreground">{label}</span><span className="text-right">{value}</span></div>}
