import { useCallback,useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { cancelP2PListing,formatINR,formatUSDC,getMyP2PListings,type P2PListing } from "@/lib/p2pApi";
import { wallet,useWallet } from "@/lib/useWallet";

export default function P2PAdvertiser(){const {userId}=useWallet();const [listings,setListings]=useState<P2PListing[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const load=useCallback(async()=>{if(!userId)return;try{setLoading(true);setError("");setListings((await getMyP2PListings()).listings)}catch(e){setError(e instanceof Error?e.message:"Could not load ads")}finally{setLoading(false)}},[userId]);useEffect(()=>{void load()},[load]);async function cancel(id:string){try{await cancelP2PListing(id);await Promise.all([load(),wallet.refreshBalances()])}catch(e){setError(e instanceof Error?e.message:"Could not cancel ad")}}return <AppShell><main className="mx-auto min-h-screen max-w-6xl space-y-6 p-6"><div><Link to="/p2p" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4"/>Back to P2P</Link><h1 className="mt-4 text-3xl font-bold">My sell ads</h1><p className="text-muted-foreground">Active ad quantities are reserved in your DEX wallet until bought or cancelled.</p></div>{!userId?<Card className="p-8 text-center text-muted-foreground">Connect and authenticate a wallet to view your ads.</Card>:error?<Card className="p-4 text-destructive">{error}</Card>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-muted/30 text-left text-xs uppercase text-muted-foreground"><tr><th className="p-4">Created</th><th className="p-4">Price</th><th className="p-4">Listed</th><th className="p-4">Remaining</th><th className="p-4">Payment</th><th className="p-4">Status</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-8 text-center">Loading…</td></tr>:listings.length===0?<tr><td colSpan={7} className="p-8 text-center text-muted-foreground">You have not posted any ads.</td></tr>:listings.map(l=><tr className="border-b last:border-0" key={l.id}><td className="p-4">{new Date(l.createdAt).toLocaleString()}</td><td className="p-4">{formatINR(l.price)}</td><td className="p-4">{formatUSDC(l.amountRaw)} USDC</td><td className="p-4">{formatUSDC(l.remainingRaw)} USDC</td><td className="p-4">{l.paymentMethod}</td><td className="p-4">{l.status}</td><td className="p-4 text-right"><Button size="sm" variant="outline" disabled={l.status!=="ACTIVE"} onClick={()=>void cancel(l.id)}>Cancel</Button></td></tr>)}</tbody></table></div></Card>}</main></AppShell>}
