import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Card } from "@/components/ui/card";
import { formatINR,formatUSDC,getP2POrders,type P2POrder } from "@/lib/p2pApi";
import { useWallet } from "@/lib/useWallet";

export default function P2POrders(){const {userId}=useWallet();const [orders,setOrders]=useState<P2POrder[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(false);useEffect(()=>{if(!userId)return;setLoading(true);getP2POrders().then(r=>setOrders(r.orders)).catch(e=>setError(e instanceof Error?e.message:"Could not load orders")).finally(()=>setLoading(false))},[userId]);return <AppShell><main className="mx-auto min-h-screen max-w-6xl space-y-6 p-6"><div><Link to="/p2p" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4"/>Back to P2P</Link><h1 className="mt-4 text-3xl font-bold">My P2P orders</h1></div>{!userId?<Card className="p-8 text-center text-muted-foreground">Connect and authenticate a wallet to view your orders.</Card>:error?<Card className="p-6 text-destructive">{error}</Card>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="border-b bg-muted/30 text-left text-xs uppercase text-muted-foreground"><tr><th className="p-4">Order</th><th className="p-4">Side</th><th className="p-4">USDC</th><th className="p-4">Payment</th><th className="p-4">Total / Receivable</th><th className="p-4">Status</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center">Loading…</td></tr>:orders.length===0?<tr><td colSpan={6} className="p-8 text-center text-muted-foreground">No P2P orders found.</td></tr>:orders.map(o=>{const bought=o.buyerId===userId;return <tr className="border-b last:border-0" key={o.id}><td className="p-4"><p className="font-mono text-xs">{o.id}</p><p className="text-xs text-muted-foreground">{new Date(o.createdAt).toLocaleString()}</p></td><td className="p-4 font-semibold">{bought?"BUY":"SELL"}</td><td className="p-4">{formatUSDC(o.amountRaw)} USDC</td><td className="p-4">{o.paymentMethod}</td><td className="p-4">{formatINR(bought?o.buyerPayable:o.sellerReceivable)}</td><td className="p-4 text-green-600">{o.status}</td></tr>})}</tbody></table></div></Card>}</main></AppShell>}
